# Generated by Django 5.0 on 2023-12-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChartView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.FloatField(default='', max_length=8)),
                ('end_at', models.FloatField(default='', max_length=8)),
                ('poinLt_1', models.FloatField(max_length=10)),
            ],
        ),
    ]
